name: flake8

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Install dependencies for testing
      run: |
        if [ -f requirements-test.txt ]; then pip install -r requirements-test.txt; fi
        pip install flake8

    - name: Lint with flake8 (fail on errors)
      run: |
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics

    - name: Lint with flake8 (warnings only)
      run: |
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
